version: '3.9'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    image: anettafm/foodgram_backend:latest
    env_file: .env
    volumes:
      - static:/backend_static
      - media:/media/
    depends_on:
      - db
  frontend:
    env_file: .env
    image: anettafm/foodgram_frontend:latest
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static
    depends_on:
      - backend
  nginx:
    image: anettafm/foodgram_infra:latest
    env_file: .env
    volumes:
      - static:/staticfiles/
      - media:/media/
    ports:
      - 8001:80