# Generated by Django 3.2.3 on 2023-08-30 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_rename_quantity_recipeingredient_amount'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='shoppinglist',
            name='unique_shopping_list_recipe',
        ),
        migrations.RenameField(
            model_name='shoppinglist',
            old_name='recipes',
            new_name='recipe',
        ),
        migrations.AddConstraint(
            model_name='shoppinglist',
            constraint=models.UniqueConstraint(fields=('recipe', 'user'), name='unique_shopping_list_recipe'),
        ),
    ]
